### ISSUE TITLE
Build App Structure, HTML

### ISSUE THREAD

**Issue by rrcampbell-exe** [rrcampbell-exe/who-would-win#2]
### Description
Once framework has been chosen and wireframe completed, need to build in appropriate HTML structure for page.

**Comment by JonnyCano** [comment]
## I figured out the styling to display the content appropriately I think and solved the fight button placement issue I was having.
<img width="960" alt="who-would-win-mock-up-vol-1" src="https://user-images.githubusercontent.com/84486012/125397383-7b0b1480-e373-11eb-8ea4-dc51a8ee8a0a.PNG">
<img width="960" alt="who-would-win-mock-up-vol-2" src="https://user-images.githubusercontent.com/84486012/125397387-7c3c4180-e373-11eb-94e6-12da62f7e052.PNG">

**Comment by rrcampbell-exe** [comment]
I love this new look, @JonnyCano! Can you push this to the `develop` branch so @jeffywk and I have access? Jeff was able to do some further styling on the button last night, and with some of what I've tinkered with this morning, I can reconcile both versions today.
